### ISSUE TITLE
Getting Traceback

### ISSUE THREAD

**Issue by jmiahman** [forkd/netbox-scanner#1]
```
Traceback (most recent call last):
  File "netbox-scanner/nbscanner", line 13, in <module>
    from nbscanner import NetBoxScanner
  File "/home/jsummers/netbox-scanner/netbox-scanner/nbscanner.py", line 195
    parsing = self.parser([f'{h[0]}/32' for h in hosts])

```

**Comment by forkd** [comment]
Probably you're using a Python version under 3.6.
Upgrade Python to 3.6+ or change that line to:

parsing = self.parser(['{}/32'.format(h[0]) for h in hosts])

Regards,
Lopes

**Comment by jmiahman** [comment]
Thank you!
